name: myenv
channels:
  - pytorch
  - pyg
  - nvidia
  - rapidsai
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.13
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - aom=3.6.1
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.7.20
  - aws-c-cal=0.6.12
  - aws-c-common=0.9.17
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.267
  - blas=1.0
  - bokeh=3.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - cachetools=5.5.2
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - contourpy=1.3.1
  - cpython=3.10.16
  - cubinlinker=0.3.0
  - cuda-bindings=11.8.6
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=11.8.86
  - cuda-python=11.8.6
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudf=23.12.01
  - cudnn=9.8.0.87
  - cuml=23.12.00
  - cupy=13.4.1
  - cupy-core=13.4.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cytoolz=1.0.1
  - dask=2023.11.0
  - dask-core=2023.11.0
  - dask-cuda=23.12.00
  - dask-cudf=23.12.01
  - dbus=1.13.6
  - distributed=2023.11.0
  - dlpack=0.5
  - double-conversion=3.3.1
  - expat=2.6.4
  - fastrlock=0.8.3
  - ffmpeg=4.4.2
  - filelock=3.17.0
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2025.3.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmock=1.16.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gtest=1.16.0
  - h2=4.2.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - jinja2=3.1.6
  - joblib=1.4.2
  - kaldi=5.5.1112
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-flight=14.0.2
  - libarrow-flight-sql=14.0.2
  - libarrow-gandiva=14.0.2
  - libarrow-substrait=14.0.2
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcudf=23.12.01
  - libcufft=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcuml=23.12.00
  - libcumlprims=23.12.00
  - libcups=2.3.3
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=8.13.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgpg-error=1.54
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - libkvikio=23.12.00
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm16=16.0.6
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libparquet=14.0.2
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=4.25.3
  - libraft=23.12.00
  - libraft-headers=23.12.00
  - libraft-headers-only=23.12.00
  - libre2-11=2023.09.01
  - librmm=23.12.00
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtasn1=4.20.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libudev1=257.4
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=2.1.4
  - libxkbcommon=1.8.0
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - llvmlite=0.40.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mdurl=0.1.2
  - mizani=0.10.0
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - narwhals=1.36.0
  - nccl=2.26.2.1
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4
  - numba=0.57.1
  - numpy=1.24.4
  - nvcomp=3.0.4
  - nvtx=0.2.11
  - openfst=1.8.3
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - orc=2.0.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=1.5.3
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - plotnine=0.12.2
  - propcache=0.2.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptxcompiler=0.8.1
  - py-xgboost=2.1.4
  - pyarrow=14.0.2
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pyg=2.6.1
  - pygments=2.19.1
  - pylibraft=23.12.00
  - pynvml=11.4.1
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.2
  - raft-dask=23.12.00
  - rapids-dask-dependency=23.12.01
  - rdma-core=55.0
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - rich=14.0.0
  - rmm=23.12.00
  - s2n=1.4.13
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.2
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - spdlog=1.11.0
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tbb=2021.13.0
  - tblib=3.1.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toolz=1.0.0
  - torchaudio=2.4.1
  - torchtriton=3.1.0
  - torchvision=0.19.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - treelite=3.9.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucx=1.15.0
  - ucx-proc=1.0.0
  - ucx-py=0.35.00
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wayland-protocols=1.41
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgboost=2.1.4
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.1.0
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - yarl=1.18.3
  - zict=3.0.0
  - zipp=3.21.0
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - docker-pycreds==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - platformdirs==4.3.6
      - protobuf==5.29.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - smmap==5.0.2
      - treelite-runtime==3.9.1
      - wandb==0.19.8
